version: '2'
services:
  magento_fu:
    build: ./Docker
    image: magento_fu
    container_name: magento_fu
    volumes:
      - ./src:/var/www/html/
    ports:
      - "8080:80"
    depends_on:
      - mysql
  mysql:
    container_name: tl_mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tl_phpmyadmin
    ports:
      - "8181:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    volumes:
      - /sessions
    depends_on:
      - mysql